# Библиотека Recommenders

## 1. Описание библиотеки

**Recommenders** – это библиотека Python для создания рекомендательных систем. Она была разработана компанией RecSys Ventures, специализирующейся на разработке решений для рекомендаций контента пользователям. Библиотека предоставляет набор инструментов и алгоритмов, которые помогают создавать персонализированные рекомендации на основе предпочтений пользователей, их поведения и других факторов.

**Основные возможности библиотеки Recommenders:**
1. **Коллаборативная фильтрация:** Один из самых популярных методов построения рекомендаций. Он основан на анализе пользовательских оценок и предпочтений, чтобы предсказать интерес к новым элементам. В библиотеке реализованы такие методы коллаборативной фильтрации, как SVD (Singular Value Decomposition), NMF (Non-negative Matrix Factorization) и другие.
2. **Контентная фильтрация:** Этот метод основывается на анализе характеристик самих элементов (например, фильмов, книг, товаров). Алгоритмы контентной фильтрации используют информацию об элементах, чтобы находить похожие элементы для каждого пользователя.
3. **Гибридные подходы:** Комбинация различных методов фильтрации позволяет создать более точные рекомендации. Например, можно объединить коллаборативную фильтрацию с контентной для достижения лучших результатов.
4. **Оценка качества рекомендаций:** Библиотека включает инструменты для оценки точности и релевантности предложенных рекомендаций. Это помогает оптимизировать модели и улучшать качество работы системы.
5. **Поддержка различных источников данных:** Recomenders поддерживает работу с различными форматами данных, включая CSV-файлы, базы данных SQL и другие источники.
6. **Визуализация и анализ данных:** В состав библиотеки входят инструменты для визуализации и анализа данных, что облегчает процесс разработки и тестирования моделей.
Интеграция с другими библиотеками: Recomenders легко интегрируется с популярными библиотеками машинного обучения, такими как Scikit-learn, TensorFlow и PyTorch, что расширяет возможности её использования.

**Установка**
1. Установка библиотеки через pip:
```
pip install recommenders
```

Библиотека Recommenders является мощным инструментом для создания рекомендательных систем. Она предлагает широкий спектр методов и алгоритмов, а также удобные средства для интеграции с другими библиотеками и источниками данных. Благодаря своей гибкости и простоте использования, она может стать отличным выбором для разработчиков, занимающихся созданием персонализированных рекомендаций.

**Документация и ресурсы**
* [Документация](https://microsoft-recommenders.readthedocs.io/en/latest/)
* [Страница на PyPi](https://pypi.org/project/recommenders/)
* [Репозиторий на GitHub](https://github.com/recommenders-team/recommenders)

In [1]:
# Импортируем необходимые библиотеки и модули:
import numpy as np   # Библиотека для научных вычислений в Python
import pandas as pd  # Работа с данными
import time          # Библиотека для работы с временем
import os            #
import sys           #  
from datetime import datetime, timedelta  # Импортируем классы для работы с датами и временем
import torch                              #
import cornac                             # 

from recommenders.datasets.python_splitters import python_random_split      # Случайное разделение данных
from recommenders.datasets.python_splitters import python_stratified_split  # Стратифицированное разделение данных
from recommenders.datasets.python_splitters import python_chrono_split      # Хронологическое разделение данных
from recommenders.models.cornac.cornac_utils import predict_ranking         #
from recommenders.utils.timer import Timer                                  #
from recommenders.utils.constants import SEED                               #
from recommenders.evaluation.python_evaluation import (map,                 #
                                                       ndcg_at_k,           #
                                                       precision_at_k,      #
                                                       recall_at_k,         #
                                                       )
from recommenders.utils.notebook_utils import store_metadata                #

from joblib import dump, load                                               # Функции для сериализации и десериализации объектов

from scipy.sparse import coo_matrix                                         # Функция для создания разреженной матрицы в формате COO
from scipy.sparse import csr_matrix                                         # Функция для создания разреженной матрицы в формате CSR

# Фиксируем начальное значение генератора случайных чисел для воспроизводимости результатов
RANDOM_SEED = 369

# Отключаем предупреждения, чтобы избежать их вывода в консоль
import warnings
warnings.filterwarnings("ignore")                              # Игнорирование всех предупреждений

# Настраиваем параметры отображения DataFrame'ов в Jupyter Notebook
pd.set_option("display.max_columns", 100)                      # Максимальное количество отображаемых столбцов
pd.set_option("display.max_rows", 200)                         # Максимальное количество отображаемых строк
pd.set_option("display.max_colwidth", 3000)                    # Максимальная ширина ячейки

# Выводим информацию о версиях используемых библиотек
%load_ext watermark
%watermark -n -u -v -iv -w

Last updated: Fri Feb 07 2025

Python implementation: CPython
Python version       : 3.12.9
IPython version      : 8.30.0

scipy       : 1.13.1
recommenders: 1.2.1
numpy       : 1.26.4
pandas      : 2.2.3
cornac      : 2.2.2
torch       : 2.5.1
joblib      : 1.4.2
sys         : 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 13:04:33) [Clang 14.0.6 ]

Watermark: 2.5.0

**Установка необходимых библиотеки**

In [2]:
# pip install --upgrade pip setuptools
# pip install recommenders
# pip install watermark
# pip install --upgrade jupyter ipywidgets
# conda install -c conda-forge optuna

* [GitHub_Watermark](https://github.com/rasbt/watermark?tab=readme-ov-file#installation-and-updating)

**Фиксируем версии установленных пакетов**

In [3]:
# conda env export > environment_recommenders.yml

In [4]:
# cоздаем пустой DataFrame для хранения результатов
results = pd.DataFrame(columns=["Model", "Time", "train_Precision@3", "test_Precision@3"])

def add_results(dataframe, model_name, elapsed_time, train_precision, test_precision):
    """Добавляет результаты работы модели в датафрейм.

    Args:
        dataframe (DataFrame): Датафрейм, содержащий результаты предыдущих моделей.
        model_name (str): Название текущей модели.
        elapsed_time (float): Время, затраченное на обучение и тестирование модели.
        train_precision (float): Значение метрики Precision@3 на обучающей выборке.
        test_precision (float): Значение метрики Precision@3 на тестовой выборке.
    
    Returns:
        dataframe (DataFrame): Обновленный датафрейм с добавленными результатами текущей модели.
    """
    new_row = pd.Series({
        "Model": model_name,
        "Time": elapsed_time,
        "train_Precision@3": train_precision,
        "test_Precision@3": test_precision
    })
    dataframe = pd.concat([dataframe, new_row.to_frame().T], ignore_index=True)
    return dataframe

## 2. Prepare data / Подготовка данных

In [5]:
# загружаем данные
data = pd.read_csv("../data/data_light_count.csv", sep=",")
# Переименуем название признаков
data = data.rename(columns={"visitorid":"userID", "itemid":"itemID", "like":"rating"})
#data = data.drop(columns="date", axis=1)
display(data)
display(data.info())

         userID  itemID  rating
0             2  216305       2
1             2  259884       1
2             2  325215       3
3             2  342816       2
4             6   65273       1
...         ...     ...     ...
470627  1407573  116453       1
470628  1407573  232069       1
470629  1407573  235724       1
470630  1407573  363109       1
470631  1407573  463766       1

[470632 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470632 entries, 0 to 470631
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   userID  470632 non-null  int64
 1   itemID  470632 non-null  int64
 2   rating  470632 non-null  int64
dtypes: int64(3)
memory usage: 10.8 MB

None

In [6]:
# Вводим обозначения переменных
COL_USER = "userID"
COL_ITEM = "itemID"
COL_RATING = "rating"
COL_PREDICTION = "rating"
COL_TIMESTAMP = "date"

### 2.1 Data split / Разделение данных

Разделение данных - одна из наиболее важных задач при оценке систем рекомендаций. Стратегия разделения сильно влияет на протокол оценки, поэтому практикующим специалистам всегда следует уделять ей пристальное внимание.

Приведенный ниже код объясняет, как применяются различные стратегии разделения для конкретных сценариев.

#### 2.1.1 Random split

Случайное разделение просто принимает набор данных и выводит фрагменты данных с учетом коэффициентов разделения.

In [7]:
# # Проводим рандомное разделение данных
# data_train, data_test = python_random_split(data, 
#                                             ratio=0.8, # Коэффициент разделения данных
#                                             seed=RANDOM_SEED) 
# print(f'Размер тренировочных данных: {data_train.shape}, Размер тестовых данных: {data_test.shape}')

In [8]:
# # Разделение на тренировочные, валидационную и тестовые выборки
# data_train, data_validate, data_test = python_random_split(data, ratio=[0.8, # можно использовать числа, пример 8
#                                                                         0.1, # можно использовать числоб пример 1
#                                                                         0.1] # можно использовать числоб пример 1
#                                                            )
# print(f'Размер тренировочных данных: {data_train.shape}')
# print(f'Размер валидационных данных: {data_validate.shape}')
# print(f'Размер тестовых данных: {data_test.shape}')

#### 2.1.2 Chronological split / Хронологическое разделение

Метод хронологического разделения берет набор данных и разбивает его по временной метке.

##### 2.1.2.1 "Filter by / Фильтрация по""

Хронологическое разделение может быть как по "пользователю", так и по "элементу". Например, если это по "пользователю" и коэффициент разделения равен 0,7, это означает, что первые 70% оценок для каждого пользователя в данных будут отнесены к одному разделению, в то время как остальные 30% - к другому. Стоит отметить, что хронологическое разделение не является "случайным", поскольку разделение зависит от метки времени.

In [9]:
# data_train_crono, data_test_crono = python_chrono_split(data, 
#                                             ratio=0.8, 
#                                             filter_by="user", 
#                                             col_user=COL_USER, 
#                                             col_item=COL_ITEM, 
#                                             col_timestamp=COL_TIMESTAMP,
#                                             )
# print(f'Размер тренировочных данных: {data_train_crono.shape}, Размер тестовых данных: {data_test_crono.shape}')

### <span style="color:red"> Данный тип разделения обеспечивает единое наличие пользователей в тестовых и тренировочных данных!!!</span>

##### 3.1.2.1 Min-rating filter / Фильтр с минимальным рейтингом

Фильтр минимальной оценки применяется к данным перед их разделением с помощью хронологического разбиения. Причина этого заключается в том, что для множественного разделения в данных должно быть достаточное количество оценок для пользователя / элемента.

Например, следующее разделение средств применимо только к пользователям, имеющим не менее 10 рейтингов.

In [10]:
# data_train_crono_rating, data_test_crono_rating = python_chrono_split(data, 
#                                                         filter_by="user", 
#                                                         min_rating=25, 
#                                                         ratio=0.8,
#                                                         col_user=COL_USER, 
#                                                         col_item=COL_ITEM, 
#                                                         col_timestamp=COL_TIMESTAMP,
#                                                         )
# print(f'Размер тренировочных данных: {data_train_crono_rating.shape}, Размер тестовых данных: {data_test_crono_rating.shape}')

### <span style="color:red"> Количество наблюдений уменьшилось, по сравнению с разбиением ранее. Мы исключаем пользователей с низкой активностью!!!</span>

#### 3.1.3 Stratified split

Метод хронологического разделения берет набор данных и разбивает его либо по пользователю, либо по элементу. Разделение стратифицировано таким образом, что один и тот же набор пользователей или элементов будет отображаться как в наборах данных обучения, так и в наборах данных тестирования.

Подобно хронологическому разделителю, filter_by и min_rating_filter также применяются к стратифицированному разделителю.

В следующем примере показано разделение выборочных данных с коэффициентом 0,8.

In [11]:
# data_train_strat, data_test_strat = python_stratified_split(data, 
#                                                 filter_by="user",
#                                                 ratio=0.8,
#                                                 col_user=COL_USER,
#                                                 col_item=COL_ITEM,
#                                                 )
# print(f'Размер тренировочных данных: {data_train_strat.shape}, Размер тестовых данных: {data_test_strat.shape}')

In [12]:
train, test = python_stratified_split(data, 
                                    filter_by="user",
                                    min_rating=20, # устанавливаем количество событий для одного пользователя
                                    ratio=0.8,
                                    col_user=COL_USER,
                                    col_item=COL_ITEM,
                                    )
print(f'Размер тренировочных данных: {train.shape}, Размер тестовых данных: {test.shape}')

Размер тренировочных данных: (119931, 3), Размер тестовых данных: (29939, 3)

In [13]:
# Удалим клиентов (холодных) из test, которых нет в train
test = test[test["userID"].isin(train["userID"])]
print(f'Размер тренировочных данных: {train.shape}, Размер тестовых данных: {test.shape}')

Размер тренировочных данных: (119931, 3), Размер тестовых данных: (29939, 3)

## 3. Коллаборативная фильтрация (Collaborative Filtering)

### 3.1 Построим модель на основе алгоритма Bilateral Variational Autoencoder (BiVAE)

**Модели двустороннего вариационного автокодировщика (BiVAE)**, применяемого для коллаборативной фильтрации. Исследование, посвященное модели BiVAE [1], было представлено на конференции WSDM'21. Все эксперименты, связанные с моделью BiVAE, описаны в этом [репозитории](https://github.com/PreferredAI/bi-vae).

Реализация модели взята из [Cornac](https://github.com/PreferredAI/cornac) [2], который является фреймворком для мультимодальных рекомендательных систем, ориентированных на модели, использующие вспомогательные данные (например, описательный текст и изображения товаров, социальные сети и т.д.).

BiVAE - это новый вариационный автоэнкодер, разработанный специально для диадических данных, где наблюдения состоят из измерений, связанных с двумя наборами объектов, например, пользователями, предметами и соответствующими рейтингами. Модель симметрична, что упрощает расширение вспомогательных данных с обеих сторон от пользователей и элементов. В дополнение к данным предпочтений, модель может быть применена к другим типам двоичных данных, таким как матрицы документ-слово, и другим задачам, таким как совместная кластеризация.

В статье также обсуждается ограниченная адаптивная априорность (CAP), предлагаемый метод построения информативных априорных значений для смягчения хорошо известной проблемы последующего коллапса. Мы намеренно опустили эту часть, чтобы не отвлекать аудиторию. Тем не менее, это очень интересно, и на это стоит взглянуть.

В этом [репозитории](https://github.com/PreferredAI/bi-vae) вы найдете более полный набор экспериментов, связанных с BiVAE.

**References**
* [1] Quoc-Tuan Truong, Salah, Aghiles, and Hady W. Lauw. "Bilateral Variational Autoencoder for Collaborative Filtering." Proceedings of the 14th ACM International Conference on Web Search and Data Mining. 2021. https://dl.acm.org/doi/pdf/10.1145/3437963.3441759
* [2] Salah, Aghiles, Quoc-Tuan Truong, and Hady W. Lauw. "Cornac: A Comparative Framework for Multimodal Recommender Systems." Journal of Machine Learning Research 21.95 (2020): 1-5. https://cornac.preferred.ai
* [3] Liang, Dawen, et al. "Variational autoencoders for collaborative filtering." Proceedings of the 2018 World Wide Web Conference. 2018.

**Описание параметров инициализации модели `cornac.models.BiVAECF`:**

1. **k** (`LATENT_DIM`) – Размер скрытого пространства. Это количество латентных факторов, которое будет использоваться для представления пользователей и элементов в пространстве пониженной размерности.
2. **encoder_structure** (`ENCODER_DIMS`) – Список целых чисел, определяющий структуру слоев энкодера. Каждый элемент списка указывает на количество нейронов в соответствующем слое. Например, `[1000, 500, 200]` означает, что у вас есть три слоя с 1000, 500 и 200 нейронами соответственно.
3. **act_fn** (`ACT_FUNC`) – Функция активации, которая используется между слоями нейронной сети. Примеры функций активации включают ReLU, Sigmoid, Tanh и другие.
4. **likelihood** (`LIKELIHOOD`) – Тип вероятностной модели, используемый для декодирования. Возможными значениями могут быть, например, `'gaussian'`, `'bernoulli'`.
5. **n_epochs** (`NUM_EPOCHS`) – Общее количество эпох (циклов) обучения модели.
6. **batch_size** (`BATCH_SIZE`) – Размер мини-батчей, используемых при обучении. Это количество образцов данных, обрабатываемых одновременно перед обновлением весов модели.
7. **learning_rate** (`LEARNING_RATE`) – Скорость обучения, которая определяет величину шага обновления весов модели после каждой итерации.
8. **seed** (`SEED`) – Начальное значение случайного числа, обеспечивающее воспроизводимость результатов экспериментов.
9. **use_gpu** – Логическое значение, указывающее, использовать ли GPU для ускорения вычислений. Здесь значение устанавливается автоматически в зависимости от доступности CUDA на устройстве.
10. **verbose** – Если установлено в `True`, то выводится информация о ходе процесса обучения (например, прогресс бар).

In [14]:
# Определяем переменные
# Количество рекомендаций для каждого пользователя
TOP_K = 3
# Параметры модели
LATENT_DIM = 50
ENCODER_DIMS = [100]
ACT_FUNC = "tanh"
LIKELIHOOD = "pois"
NUM_EPOCHS = 10
BATCH_SIZE = 256
LEARNING_RATE = 0.001

**Cornac Dataset**

Для работы с моделями, реализованными в Cornac, нам нужно создать объект класса [Dataset](https://cornac.readthedocs.io/en/latest/data.html#module-cornac.data.dataset).

Класс Dataset в Cornac служит основным объектом, с которым будут взаимодействовать модели. Помимо преобразования данных, класс Dataset предоставляет множество полезных итераторов для перебора данных, а также поддерживает различные методы выборки отрицательных примеров.

In [15]:
# Создаем Dataset Cornac
train_set = cornac.data.Dataset.from_uir(train.itertuples(index=False), seed=SEED)
print("Количество клиентов: {}".format(train_set.num_users))
print("Количество товаров: {}".format(train_set.num_items))

Количество клиентов: 2348
Количество товаров: 47810

In [16]:
# Определяем параметры модели и обучаем ее
bivae = cornac.models.BiVAECF(
    k=LATENT_DIM,                        # Размер скрытого пространства (количество латентных факторов)
    encoder_structure=ENCODER_DIMS,      # Структура слоев энкодера (список размеров скрытых слоев)
    act_fn=ACT_FUNC,                     # Функция активации для нейронной сети
    likelihood=LIKELIHOOD,               # Вероятностная модель (например, 'gaussian', 'bernoulli')
    n_epochs=NUM_EPOCHS,                 # Количество эпох обучения
    batch_size=BATCH_SIZE,               # Размер батча при обучении
    learning_rate=LEARNING_RATE,         # Скорость обучения
    seed=SEED,                           # Случайное зерно для воспроизводимости результатов
    use_gpu=torch.cuda.is_available(),   # Использовать GPU, если доступен
    verbose=True                         # Выводить информацию о процессе обучения
)

with Timer() as t:
    bivae.fit(train_set)
print("Took {} seconds for training.".format(t))

  0%|          | 0/10 [00:00<?, ?it/s]

Took 101.7160 seconds for training.

In [17]:
# # Сохраняем модель в файл
# dump(bivae, "model/model_BiVAECF.joblib")

**Prediction and Evaluation**

Теперь, когда наша модель обучена, мы можем создавать ранжированные списки для рекомендаций. Все рекомендательные модели в Cornac предоставляют методы rate () и rank () для прогнозирования номинальной стоимости товара, а также ранжированного списка товаров для данного пользователя. Чтобы использовать текущие схемы оценки, мы будем использовать функции predict() и predict_ranking() внутри cornac_utils для получения прогнозов.

Давайте измерим рекомендательную эффективность модели, используя показатели рейтинга top-K.

In [18]:
# Формируем рекомендации
with Timer() as t:
    all_predictions = predict_ranking(bivae, train, usercol="userID", itemcol="itemID", remove_seen=True)
print("Took {} seconds for prediction.".format(t))

Took 232.9211 seconds for prediction.

In [19]:
# Производим расчет и печать метрики 
eval_precision = precision_at_k(test, all_predictions, col_prediction="prediction", k=TOP_K)
print("Precision@K:\t%f" % eval_precision)

Precision@K:	0.004401

In [20]:
# Получение рекомендаций для конкретного пользователя
user_id = 890980
all_predictions[all_predictions["userID"] == user_id].sort_values(by="prediction", ascending=False).head(3)

          userID  itemID  prediction
70715672  890980   46232     1.00000
70748893  890980  369447     1.00000
70756789  890980  446820     0.98895